name: CI

on:
  push:
  workflow_dispatch:

jobs:
  release-latest:
    name: "Release"
    if: ${{ github.repository == 'Its-Alex/restic-ftp-docker' && contains(github.ref, 'refs/heads/main') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: itsalex/restic-ftp
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
